### ISSUE TITLE
Missing required error components, refreshing...

### ISSUE THREAD

**Issue by tpompon** [UretzkyZvi/nextjs-typescript-tailwind-ionic-starter#1]
Hey, first thank you for the initiative to make a version of this boilerplate using Next.js 14.
I wanted to start a project with this stack and I was searching for a good boilerplate to win time.

**Issue**

After running `npm i && npm run dev`, the output on `localhost:3000` is `missing required error components, refreshing...`

 `⨯ Error: Cannot find module '/nextjs-typescript-tailwind-ionic-starter/build/server/middleware-manifest.json'`

Have you faced this issue as well and do you know how to fix it?

Thanks,
Thomas

**Comment by UretzkyZvi** [comment]
Hey Thomas,

Great news! Based on your feedback, I've made some updates to ensure a smoother development experience with the boilerplate. 🚀 Here's a quick summary of the changes:

1. **Fixed the configuration issue** in `next.config.mjs` to ensure compatibility with both web and mobile platforms. Now, during `output: 'export'`, Next.js will export to the 'out' folder, which aligns perfectly with Capacitor's `webDir: "out"` setting.

2. **Updated the README file** with enhanced setup instructions, including the addition of iOS and Android platforms and the installation of Android Studio and Xcode. This should guide you seamlessly through setting up your development environment for both Android and iOS.

3. **Introduced new npm scripts** to streamline the development and build process:
   - ``npm run build:dev` for quick building your project without the lint validation.
   - `npm start` with experimental HTTPS support.
   - Shortcut commands for Android and iOS like `start:android`, `start:ios`, `open:android`, and `open:ios` to build, sync, and open your app in the respective environment with ease.

Please pull the latest changes and give it another go. Your feedback is incredibly valuable, and I'm here to help with any further issues or questions you might have.

Best,

**Comment by tpompon** [comment]
So fast Greg!

I just pulled the update and it works just perfect now, thank you very much 🙏🏻
